export const xieJinwenBaseCase = {
  caseId: 'xie-jinwen-base',
  name: '謝進文',
  gender: 'male',
  appGender: '男',
  input: {
    inputMode: 'manual',
    year: '',
    month: '',
    day: '',
    hour: '',
    uncertainHour: false,
    manualPillars: {
      year: '丁卯',
      month: '甲辰',
      day: '癸丑',
      hour: '壬子',
    },
    name: '謝進文',
    gender: '男',
    analysisYear: 2026,
    topic: '整體運勢',
    query: '',
    compoundSurname: '',
    birthCity: '',
    birthLongitude: '',
    solarTimeMode: 'none',
    timezone: 'Asia/Taipei',
  },
  expectedCore: {
    pillars: {
      year: '丁卯',
      month: '甲辰',
      day: '癸丑',
      hour: '壬子',
    },
    dayStem: '癸',
    dayElement: '水',
  },
  expectedTenGods: {
    stems: {
      year: '偏財',
      month: '傷官',
      day: '日主',
      hour: '劫財',
    },
    hiddenStems: {
      year: [{ stem: '乙', tenGod: '食神' }],
      month: [
        { stem: '戊', tenGod: '正官' },
        { stem: '乙', tenGod: '食神' },
        { stem: '癸', tenGod: '比肩' },
      ],
      day: [
        { stem: '己', tenGod: '七殺' },
        { stem: '癸', tenGod: '比肩' },
        { stem: '辛', tenGod: '偏印' },
      ],
      hour: [{ stem: '癸', tenGod: '比肩' }],
    },
  },
  expectedRelations: {
    allowed: ['卯辰害', '子丑合', '子卯無禮之刑', '子辰半合水'],
    forbidden: ['辰自刑', '申子辰水局', '子丑合化土', '合化土', '完整三合水局'],
  },
  expectedFlow: {
    year: { year: 2026, pillar: '丙午', stemTenGod: '正財' },
    months: [
      ['正月', '庚寅'],
      ['二月', '辛卯'],
      ['三月', '壬辰'],
      ['四月', '癸巳'],
      ['五月', '甲午'],
      ['六月', '乙未'],
      ['七月', '丙申'],
      ['八月', '丁酉'],
      ['九月', '戊戌'],
      ['十月', '己亥'],
      ['冬月', '庚子'],
      ['臘月', '辛丑'],
    ],
  },
  expectedDayun: {
    directionLabel: '逆行',
    pillars: ['癸卯', '壬寅', '辛丑', '庚子', '己亥', '戊戌', '丁酉', '丙申'],
  },
  expectedStrengthV2: {
    labels: ['中和偏弱', '身偏弱'],
    confidence: '中',
    useful: ['金', '水'],
    patternIncludes: ['正官格傾向', '傷官見官'],
  },
  expectedName: {
    strokes: { 謝: 17, 進: 15, 文: 4 },
    wuge: {
      天格: 18,
      人格: 32,
      地格: 19,
      外格: 5,
      總格: 36,
    },
  },
  expectedShensha: {
    verified: [
      '天乙貴人',
      '文昌貴人',
      '桃花',
      '華蓋',
      '將星',
      '紅鸞',
      '天德貴人',
      '月德貴人',
      '福星貴人',
      '祿神',
      '學堂',
      '空亡',
      '寡宿',
      '災煞',
    ],
    notVerifiedOrNotApplicable: [
      '驛馬',
      '天喜',
      '羊刃',
      '孤辰',
      '亡神',
      '劫煞',
      '天赦',
      '元辰',
    ],
    aliasOnly: ['大耗'],
  },
}

export const SYSTEM_FORBIDDEN_PHRASES = [
  'undefined',
  'null',
  '[object Object]',
  '辰自刑',
  '申子辰水局',
  '子丑合化土',
  '合化土',
  '2026金水喜用之年',
  '2026 金水喜用之年',
  '正月己丑',
  '純正官格',
  '喜用神絕對為金水',
  '必定發財',
  '一定升遷',
  '必定破財',
  '必有災',
  '身弱必發不了財',
  '姓名五格皆吉',
  '五格大吉',
  '姓名大吉',
  '姓名保證大吉',
  '吉神匯聚',
  '凶煞聚集',
  '必定婚喜',
  '保證逢凶化吉',
  '空亡必定失敗',
  '災煞必有血光',
  '寡宿必婚姻不順',
  '大耗必定破財',
  '元辰必有災',
  '需搭配完整旺衰模型驗證',
  '吉凶仍待81數理與三才表校驗',
  '吉凶結論仍待校驗',
  '吉凶仍待校驗',
  '目前不輸出吉凶定論',
  '81數理吉凶、三才配置與字五行尚未校驗',
  '時支子為水強根',
  '時支藏癸為水強根',
  '壓力較高：無',
  '五月 約芒種至小暑 甲午 傷官 此月平穩',
  '六月 約小暑至立秋 乙未 食神 此月平穩',
  '九月 約寒露至立冬 戊戌 正官 此月平穩',
  '正月庚寅、二月辛卯，金水印星透出',
  '三月壬辰、四月癸巳，水比劫幫身，團隊合作順利',
  '冬月庚子、臘月辛丑，金水印比幫身，年終收尾順利',
  '年柱丁卯偏財，月柱甲辰傷官，日柱癸丑為日主坐七殺之地，時柱壬子劫財',
  '年柱丁卯偏財',
  '月柱甲辰傷官',
  '時柱壬子劫財',
  '日柱癸丑正官',
  '日柱癸丑為正官',
  '日干癸為正官',
  '日支丑為正官',
  '尚未產生 AI 喜用補強建議',
  '尚未產生喜用補強建議',
  '身強弱：偏弱，系統初判',
  '命局水偏旺，土亦重',
  '有助於平衡命局能量',
  '保證開運',
  '必定有效',
  '一定改善',
  '絕對準確',
  '命中注定不可改',
  '癸水日主，也就是癸水日主',
  '日主為癸水，也就是癸水日主',
  '報告建議喜用金、水，白話就是喜用金、水',
  '喜用金、水，白話就是喜用金、水',
  '喜用金、水，也就是喜用金、水',
  '後天調整。。',
  '。。',
]
